In [1]:
import torch

## Creating matrices and tensors

Initialising empty matrix will be filled with values whatever are in memory:

In [2]:
x = torch.empty(5,4)
x

tensor([[1.5637e-01, 3.2501e+33, 4.3712e+24, 3.4554e+30],
        [1.8545e+25, 1.7539e+19, 1.6635e+22, 8.1446e-33],
        [1.3563e-19, 1.6114e-19, 2.0706e-19, 7.2939e+22],
        [7.3652e+31, 7.4333e+28, 3.9559e-14, 4.7477e+27],
        [1.1703e-19, 1.5637e-01, 4.9593e+28, 8.0453e+20]])

Initialising random matrix:

In [3]:
x = torch.rand(5,4)
x

tensor([[0.2076, 0.7508, 0.1147, 0.5039],
        [0.7195, 0.9649, 0.4138, 0.3861],
        [0.0907, 0.1535, 0.1238, 0.2412],
        [0.8158, 0.1968, 0.3219, 0.9158],
        [0.3283, 0.3439, 0.2350, 0.3637]])

Zero matrix of type integer:

In [4]:
torch.zeros(5,4, dtype=torch.long)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

Creating tensor:

In [5]:
x = torch.tensor([5.2, 2])
x

tensor([5.2000, 2.0000])

Sizes:

In [6]:
x.size()

torch.Size([2])

## Operations

Addition:

In [7]:
y = torch.rand(4,2)
print(y)
print(x)
#Same:
print(x+y)
print(torch.add(x,y))

tensor([[0.1106, 0.9906],
        [0.2514, 0.1372],
        [0.5660, 0.1763],
        [0.4129, 0.4348]])
tensor([5.2000, 2.0000])
tensor([[5.3106, 2.9906],
        [5.4514, 2.1372],
        [5.7660, 2.1763],
        [5.6129, 2.4348]])
tensor([[5.3106, 2.9906],
        [5.4514, 2.1372],
        [5.7660, 2.1763],
        [5.6129, 2.4348]])


In [8]:
#Addition in place means that x is added to y, so y is changed
y.add_(x)
y

tensor([[5.3106, 2.9906],
        [5.4514, 2.1372],
        [5.7660, 2.1763],
        [5.6129, 2.4348]])

Reshaping:

In [9]:
#reshape y to 1x8 matrix:
y.view(1,8)

tensor([[5.3106, 2.9906, 5.4514, 2.1372, 5.7660, 2.1763, 5.6129, 2.4348]])

Converting to numpy array:

No numpy import needed

In [10]:

a = torch.ones(5)
print(a)
b = a.numpy()
b

tensor([1., 1., 1., 1., 1.])


array([1., 1., 1., 1., 1.], dtype=float32)

Changing np array changes torch tensor automatically:

In [11]:
import numpy as np 

a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

np.add(a,1, out=a)

print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CUDA tensors:

In [12]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([6.2000, 3.0000], device='cuda:0')
tensor([6.2000, 3.0000], dtype=torch.float64)


In [13]:
#Create tensor and move it to CUDA GPU:
test_number = torch.tensor([4,5,2.1])
print(test_number)
test_number.to("cuda")

tensor([4.0000, 5.0000, 2.1000])


tensor([4.0000, 5.0000, 2.1000], device='cuda:0')